[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hbic-computing"
authors = [{name = "James Bartolotti", email = "jbartolotti2@kumc.edu"}]
dynamic = ["version", "description"]
